[package]
name = "raph/bitnet"
description = "Buffer-based networking library for Roblox"
version = "3.0.0"
license = "MIT"
authors = ["Raph"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
exclude = ["rokit.toml"]

[dependencies]
