[package]
name = "minecoiii2/bitnet"
description = "Lightning-fast buffer-based networking library for Roblox"
version = "3.1.0"
license = "MIT"
authors = ["Raph"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/minecoiii2/bitnet"
exclude = ["rokit.toml", "build.project.json", "networking.project.json", "Networking.luau", ".github"]

[dependencies]
